### ISSUE TITLE
Prompt unusable - Requests gpg key list each time, 1.5s each

### ISSUE THREAD

**Issue by julian-klode** [pazz/alot#1064]
A new CryptoKeyCompleter instance is created each time you open the prompt, listing all keys in the keyring. This is slow: A single call to crypto.list_keys() takes about 1.5 seconds, probably due to one of the keys being on a smart card (and gpg checking if the smart card is there, I guess).

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        6    9.007    1.501    9.057    1.510 alot/completion.py:565(__init__)

**Comment by dcbaker** [comment]
I actually ran into this recently, a corrupt key in my keyring caused gpg to take over 10 minutes to iterate the keys, so I have thought about this a bit. The problem I see with caching is we need a cheap, reliable way to know when we need to update the keys in the CryptoCompleter instance. I'm not familiar enough with GPG or GPGME to know if there is such a value or what to get it. Ideas very welcome.

**Comment by meskio** [comment]
I use keys in smartcards and I don't notice this slowness.

@julian-klode is `gpg --list-keys` as slow as in alot? Do you have a huge keyring? is your keyring in the old gpg keyring format?

Since gnupg >= 2.1 there is a new keyring format (keybox), it's main improvement is to be fast for big keyrings. Are you using this keyring or the old gpg format? You can check if you have a `~/.gnupg/pubring.kbx` or a `~/.gnupg/pubring.gpg`. If you are using the old format will be nice if you can use the command `migrate-pubring-from-classic-gpg` to upgrade and check if it's still slow.

**Comment by julian-klode** [comment]
It's a normally sized keyring I'd say (about 970 keys) - surprisingly the kbx was empty.  I migrated to kbx now and it's at 0.6 - but that's still too slow.

**Comment by pazz** [comment]
@julian-klode  could you try if#1066 fixes this for you?

**Comment by julian-klode** [comment]
@pazz That seems to solve the issue.

**Comment by pazz** [comment]
OK great, thanks for confirming.

**Comment by pazz** [comment]
I'm closing this issue then, as #1066 got merged. Thanks guys.
