### ISSUE TITLE
Mail sent by sign adress instead of from address

### ISSUE THREAD

**Issue by NoctuaNivalis** [pazz/alot#1110]
I use alot (msmtp) to send mails with to accounts. I use the same GPG key to sign both mails. Things used to work, but since commit 2504de648dd6413625387924baaca126eac68016 or 3995747c4efed39a74e75b5c11061574bc1e8cd8 of @dcbaker, all mails are sent through the account I sign with, not the one in the "from" header.

I'm mentioning the GPG part because of the contents of the mentioned commit. I can't image something else causing this commit to influence the sender.

**Comment by lucc** [comment]
Can you post a minimal config to reproduce this (you can anonymize the address and key just make it clear which are the same)?

**Comment by NoctuaNivalis** [comment]
Anonymize? *giggle.* Here's my [configuration file](https://github.com/NoctuaNivalis/dotfiles/blob/master/config/alot/config).

**Comment by dcbaker** [comment]
I'm very certain it is not the second one, that just changes the way we format the text to be signed or verified, not which gpg key is used. I think it is the second one, and I think you're hitting an odd corner, if my guess is right.

I fetched your key and looked at it, it is configured to sign for your gmail, but your gmail account in alot isn't configured to use it. Could you copy the `gpg_key` line to your gmail account and see if you still have the problem? I'm trying to narrow down what's actually happening here, if you still have the problem I'd like to know so we can add a test and fix the bug.

**Comment by lucc** [comment]
Do you have some hooks that modify the from line in emails that you `:compose`? Because https://github.com/pazz/alot/blob/2504de648dd6413625387924baaca126eac68016/alot/commands/envelope.py#L497-L498 look to me as if the email address to look up the key is taken from the envelope. And I assume the envelope from address should come from the account you use.

Another question: Which account do you consider "the one you sign with"? Because `[[gmail]]` has the address you sign with and `[[ugent]]` has the `gpg_key` you sign with.

Also how do you see that the mail is send from the wrong account? Do the msmpt logs say so or does the envolope from address magically change inside alot, or ...?

@pazz and @dcbaker what can I do to for a minimal setup to test something like this? Do you just create a new unix user to use the differnt config files for alot and msmtp and gpg and notmuch? Because in this case I assume it is not enough to just change the config file of alot.

**Comment by dcbaker** [comment]
Oooooh, that's odd. It's a weird interaction between my patch and sign_by_default=True.

**Comment by dcbaker** [comment]
And my failure to use the API's correctly

**Comment by NoctuaNivalis** [comment]
> Could you copy the gpg_key line to your gmail account and see if you still have the problem?

Yeah, same problem. Actually, before this change my gmail account did use the GPG key, but it selected it automatically because the GPG key belongs to the mail address.

> Do you have some hooks that modify the from line in emails that you :compose?

I don't have any hooks.

> Which account do you consider "the one you sign with"?

I only (and always) sign with the mentioned PGP key, which belongs to my gmail address. The problem occurs when I try to send with my ugent address.

**Comment by pazz** [comment]
I may have stumbled on a related issue: it seems that on current master, alot *always* sends from the first account, no matter the `from` header. The debug logs is not very verbose on this, I'll investigate.
But it could very well be the same issue you're having, in which case it is unrelated to the gpg stuff..

**Comment by NoctuaNivalis** [comment]
It could indeed be, if I failed to git bisect correctly (which I might have).

**Comment by pazz** [comment]
@NoctuaNivalis can you try the branch from #1115 to see if that fixes your problem? I'm pretty sure it will..

**Comment by NoctuaNivalis** [comment]
Seems fixed indeed. Turns out I'm really bad at bisecting.
