### ISSUE TITLE
PGP EFAIL vulnerability

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1241]
In case other's haven't seen it, there's a vulnerability when PGP and HTML are combined, and an attacker can retrieve the encrypted message, modify it, and resend or replace the original. When the message is decrypted, HTML in the mail can be used to forward the plaintext message.

Here's a [message[(https://lists.gnupg.org/pipermail/gnupg-users/2018-May/060315.html) from gnupg about mitigation techniques. I'm not sure yet if we're vulnerable, but we should look into it.

**Comment by mturquette** [comment]
Would a global configuration to disable crypto functions be a suitable workaround?

Such a config would have been super helpful to me back in 2016 when I switched to GPG v2.1 and alot stopped working. Here is a super shitty hack that I did back then to disable all crypto support in alot:

https://github.com/mturquette/alot/commit/3635055f9527e1bf0140dabac77f2a161d4f89b8

**Comment by dcbaker** [comment]
@teythoon I wrote a test based on [this](https://lists.gnupg.org/pipermail/gnupg-users/2018-May/060323.html) message. gpgme fails when using the default cipher with no MDC (yay!), but if the cipher is 3DES it happily decrypts it with no warnings or errors (boo).

I do think it would be pretty useful to have an option to not render parts of encrypted emails by default. that shouldn't be too hard to wire up and would side step a lot of issues like this.

**Comment by dcbaker** [comment]
and by render I mean for non-plain text parts.

**Comment by drebs** [comment]
While talking to @dcbaker on IRC, we got to the following understanding:

* The Efail vulnerability depends on the following things happening sequentially:
  1. Individual MIME parts are concatenated (including the middle decrypted part).
  2. The result of the concatenation is rendered as HTML.
  3. External content present in the rendered HTML is loaded from the internetz.
* `alot` handles each MIME part individually using whatever is defined in `~/.mailcap`, and only then concatenates the rendered text to display.
* Because of that, `alot` should not be vulnerable to Efail.

Can someone confirm that this understanding is correct?

**Comment by teythoon** [comment]
@dcbaker: If GnuPG ignores the missing MDC in case of 3DES, this is a
GnuPG bug that should be reported and fixed.

drebs writes:
> While talking to @dcbaker on IRC, we got to the following understanding:
>
> * The Efail vulnerability depends on the following things happening sequentially:
>   1. Individual MIME parts are concatenated (including the middle
>   decrypted part).

No, this is only one variant.  The other relies on the malleability of
the cipher mode used in OpenPGP.

>   2. The result of the concatenation is rendered as HTML.
>   3. External content present in the rendered HTML is loaded from the internetz.
> * `alot` handles each MIME part individually using whatever is defined
>   in `~/.mailcap`, and only then concatenates the rendered text to
>   display.
> * Because of that, `alot` should not be vulnerable to Efail.

Whether or not alot is vulnerable depends on what people use to render
html.  If one uses a browser that loads external sources, then said user
is vulnerable iff a bad or missing MDC still allows the user to view
this mime part.

**Comment by drebs** [comment]
> Whether or not alot is vulnerable depends on what people use to render
html.  If one uses a browser that loads external sources, then said user
is vulnerable iff a bad or missing MDC still allows the user to view
this mime part.

Thanks for your answer.

So what should be the responsibility of `alot` as a MUA that does not provide HTML rendering and external loading by itself? Should it avoid honoring mailcap for encrypted MIME parts? Are there other options?

**Comment by NoctuaNivalis** [comment]
As alot doesn't provide HTML rendering and external loading, it's not responsible. The only thing alot can do here is not concatenating the parts (which it doesn't).

**Comment by teythoon** [comment]
That is a good question.  The safest thing to do is to avoid any interpretation of the data, and to say "Sorry, this message is corrupted".  However, that prevents interoperability with clients that don't send SEIP/MDC packets but the old SED packets (then again, maybe that is a good thing (TM)).

In any case, no mime parts should be fed into any external program.

Furthermore, the documentation should clearly state that no external viewer should load external resources.  This is important even in the absence of an attack, since loading external resources leaks the fact that (and when, how, and from where...) the message is viewed and is a privacy problem.

@NoctuaNivalis, this is not correct.  The cipher mode used by OpenPGP (CFB) allows one to execute the attack by modifying a single mime part.

**Comment by varac** [comment]
> Whether or not alot is vulnerable depends on what people use to render html

It would be great to document best practices how - and how not - to integrate external html rendering without EFAILing.

**Comment by dcbaker** [comment]
@teythoon. gpgme rejects modern ciphers that don't use MDC, right? At least when I poked at it with messages that had MDC disabled python-gpgme gave me a generic decryption error.

**Comment by teythoon** [comment]
Dylan Baker <notifications@github.com> writes:

> @teythoon. gpgme rejects modern ciphers that don't use MDC, right?

AIUI yes.  Sorry, but I cannot be more specific from the top of my head.

> At least when I poked at it with messages that had MDC disabled python-gpgme gave me a generic decryption error.

That is a good sign, however, OpenPGP is designed to be streamable, and
GnuPG defers any buffering to the consumer in the hope that the
application knows better how to handle that.

Iirc, if you use GPGME so that it gives you a buffer, you should be
fine.  You can in fact get GPGME to stream data to you, and then you
see the plaintext before its integrity is confirmed.  But I would be
very surprised if this is used in alot.

**Comment by dcbaker** [comment]
I'm going to close this. I think in general alot is not vulnerable, due to the fact that we don't handle HTML by default (although depending on how HTML handling is configured by the user it could be vulenerable), although AFAICT the way we recommend to use w3m is not vulnerable, and gpgme is not vulnerable due to it's use of MDC for all ciphers that support it.
