### ISSUE TITLE
chardet takes way too long

### ISSUE THREAD

**Issue by mjg** [pazz/alot#1253]
For large attachments, determing the encoding with chardet takes way too long - in the order of minutes for a few megabytes.

POC patch upcoming.

**Comment by lucc** [comment]
I noticed that too.

Why are we even scanning the blobs? I found a message which declares a content-type for the attachment but cadet still scans the blob.

**Comment by lucc** [comment]
If you search for `is:attachment and mimetype:image/jpeg` you would probably find big files to try this.  And as notmuch knows that it is a blob of type image/jpeg the question is why can we not get this data from notmuch or the email header/ content part header but have to parse the blob?

**Comment by pazz** [comment]
@lucc the reason is elaborated in the commit msg of 0b5f8bf. I have two thoughts:

1) cutting off the file after some prefix kind of defeats the purpose of the confidence of the result and of course also means less accurate findings.
2) It looks like alot is not just using this for attachments (where it makes sense) but for *all mails*
via `alot.db.message.Message.get_email`, which calls `alot.db.utils.message_from_bytes`, which calls `alot.helper.try_decode`, which calls the `guess_encoding` stuff.
I'd be better to avoid guessing the encoding as much as possible, relying on header values..

**Comment by lucc** [comment]
I assume it makes sense only if there is some potentially broken content-type and encoding for the message part in question. So for attachments with base64 this should not be necessary. And if we leave out attachments with base64 encoding I think we are already getting rid of the biggest files hence the biggest delays.

@dcbaker can you clarify what kind of message parts produced the problem that was fixed in 0b5f8bf? It was merged with the py3 branch (#1055).

**Comment by mjg** [comment]
A few remarks from my side:

1. The patch is meant to be a Proof Of Concept: Show that this call is really the bottle-neck. (At first I thought alot would hang - it's really minutes.) 1024 lines is just an arbitrary finite number that feels finite to humans, too.
2. `chardet` sets up several state machines (for each possible encoding type) and feeds the input byte by byte to each of them - you definitely don't want to do this with large blobs.
3. `guess_encoding()` is about the encoding, not the mime type. You should not need a lot of data - a few lines should be sufficient already.
4. I would have hoped that the detector stops once it's confident to have reached a conclusion, but that never seems to happen on these attachment blobs (PDFs in my case). Therefore the cut-off.
5. `chardet` is better at "recognizing" windows-1252 (0b5f8bf14 talks about decoding it) simply because that's the fallback result when it cannot decide between several 7bit single byte encodings.

And all this because Exchange sends corrupted e-mails...

**Comment by pazz** [comment]
I believe that the way to go is to retire our homebres `message_from_bytes` helper alltogether (https://github.com/pazz/alot/blob/master/alot/db/utils.py#L286).

the patch [here](https://github.com/pazz/alot/commit/6c68e2e1712e6a849f30f98e46921f2841f16a31) 
speeds up message loading even further for me.

I need some help with the failing tests though!

**Comment by mjg** [comment]
The more I read about chardet the more I think one should avoid it... Even Mozilla does not seem to recommend it any more. I'll test with 6c68e2e from @pazz .

BTW: Are there more functionality changes that sneaked in with the py3k branch? Just saying :)

**Comment by mjg** [comment]
So, it turns out that some of alot's message_from_ functions add extra headers for signatures and encryption, and  6c68e2e turned that off. [Here](https://github.com/mjg/alot/commit/7fcfa019f531442c61b3426e87eddb841fccb717) is a version of that commit which keeps adding the headers but uses the email module. (Joint authorship, whatever you prefer...) tests pass, and fat e-mails parse :)

**Comment by lucc** [comment]
Should we wait for @dcbaker to comment on this? Otherwise I think you can open a PR based on that commit. Then we can properly review it.

Also: I think we should add some tests. Maybe it is time to introduce a mail corpus into the test. (Or store byte-string-messages in the test files.)  @dcbaker can you provide one of the problematic messages that you mentioned in 0b5f8bf cleaned up for the tests?

**Comment by pazz** [comment]
re test-corpus: I recently cooked up a proposal for this [here](https://github.com/pazz/alot/tree/test-corpus).

I am happy to go with something like you've suggested, @mjg. I'm not so sure about the name `message_from_message` though :-)

**Comment by mjg** [comment]
_Namen sind Schall und Rauch_

Some message_from_ check for signatures, some don't. I'm not even sure whether every caller that calls a checking function needs that info. So, a proper strategy would be:

1. revert the chardet commit
2. rename existing functions to checked_message_ (or anything else, your call) if they check for signatures and such.
3. Refactor as in the commit I mentioned (introducing checked_message_from_message_).
4. Use email module as in your commit above.

Waiting for name suggestions :)

**Comment by pazz** [comment]
forget what I said about my test-corpus branch. It only contains one nasty mail and I haven't documented what it triggers. In any case, I fully agree that adding a test corpus would be neat. This way we would'nt have to hardcode message sources into the test classes.

Regarding the extra headers: I dont remember adding this myself and I do not fully understand why it is necessary. Is it to check the validity of encryption at the point where messages is parsed, so that the UI only needs to draw according to the artificial header? If so, perhaps this extra interpretation of messages should be optional, in case someone wants to use alot to display a message as is?

@mjg: sounds like a decent plan. Let's wait for what @dcbaker has to say about it.

**Comment by pazz** [comment]
@mjg: is there a PR for you patch? I cannot find it

**Comment by mjg** [comment]
@pazz no PR yet, we were waiting for input from @dcbaker. Also, I've been using my branch without problems so far but may have replaced message_from_ by decrypted_message_ one time too often - when reediting the to:-list after editing a message, I get a few warnings about missing keys - I don't remember getting those before.

**Comment by pazz** [comment]
[here](https://github.com/pazz/alot/issues/1253) is a fix for the key issue.
I think it'd be easiest if you would just send a PR for this patch here (the github infrastructure for reviews and approvals only works for PR's not for issues.)

**Comment by mjg** [comment]
Here is not here, but where? :)

**Comment by pazz** [comment]
sorry, c&p error: https://github.com/pazz/alot/pull/1252

**Comment by dcbaker** [comment]
Closed via #1266
