### ISSUE TITLE
Multiple selection of messages

### ISSUE THREAD

**Issue by mjuarezm** [pazz/alot#1391]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to tag messages that match a query.

**Describe the solution you'd like**
I've seen in `alot` documentation that the API supports such operation on the database but there seems not to be a command for it. It would be great to have a `tagall` command or similar.

**Describe alternatives you've considered**
Currently I'm still tagging emails one-by-one.

**Comment by lucc** [comment]
How about `search what ever you query ; tag --all some-new-tag`? Where did you look any how could the documentation be improved in this regard?

**Comment by mjuarezm** [comment]
I'm actually trying to untag a search of emails, I'm using the following variation of your command and it doesn't recognize the tags:
`search what ever you query ; tag --all -new-tag`

I looked in the user manual: https://alot.readthedocs.io/en/latest/

 I think I was confused because the documentation for '--all' says: "tag all messages in thread", which I interpret as a message thread, not a buffer. I also did not know you could pipe alot commands using semicolon.

Thanks!

**Comment by lucc** [comment]
The semicolon is not a pipe in the shell sense as no data is send from the first command to the second. It is sequential execution of several commands typed in one command line.

Try `untag --all ...` instead of `tag --all ...`. The syntax for `tag` and `untag` is not the same as for `notmuch tag`.

On the exact page you linked there is no documentation for a `tag` command.  There is one for [thread mode](https://alot.readthedocs.io/en/latest/usage/modes/thread.html) and one for [search mode](https://alot.readthedocs.io/en/latest/usage/modes/search.html). Obviously the one in thread mode will tag `--all` messages of the thread and the one in search mode will tag `--all` in the search.

**Comment by mjuarezm** [comment]
Thanks @lucc. Everything is clear except the use of the term 'thread' in documentation about search mode: 

https://alot.readthedocs.io/en/latest/usage/modes/search.html?highlight=tag

> [..] add tags of all messages in the **thread** that match the current query

I still think this can be confusing as `tag` is not applied on message thread but on a search result, as it is correctly explained in the docstring for the `--all` parameter. I hope it helps.

**Comment by lucc** [comment]
Ok, these parts of the docs are probably autogenerated and the command might be defined only once and be used in both modes. We should update the docstring to cover both cases.

**Comment by mjuarezm** [comment]
Thanks for all the help and for maintining alot! I've just started using it and I love it.
