### ISSUE TITLE
Cannot overwrite defaults for `sent_tags` and `draft_tags` 

### ISSUE THREAD

**Issue by sgelb** [pazz/alot#1412]
**Describe the bug**

If the user sets the config values for `sent_tags` and `draft_tags`, the hardcoded default values `sent` and `draft` are not overwritten, but added to the list of customized tags. This was already mentioned in #918, but has not been pursued further.

**To Reproduce (on the example of `sent_tags`)**
1.  Set `sent_tags` for some account in your config: `sent_tags = my_custom_tag` 
2.  Send a message from this account
3.  The sent message has two tags: `my_custom_tag` and `sent`

**Expected behaviour**
- The sent message has one tag, `my_custom_tag` and default tag `sent` is not added

For me this is unwanted behaviour. But as it exists like this for years now, I'm not sure if I should open a PR. Any comments?

**Comment by lucc** [comment]
As the docs explicitly say
> **sent_tags**
>  list of tags to automatically add to outgoing messages
> **Type** string list
> **Default** sent

I would agree that the expected behaviour should be to not set the `send` tag when the option is set to something else.

Con: I would expect *every* message that I send to have the `send` tag. That is just how I understand my tags.
Pro: It is harder to remove the `send` tag on some messages than to specify `send_tags=my_cust,send`.

Conclusion: I'm in favor of a PR.
