### ISSUE TITLE
In the thread view, the focused message's summary is rendered incorrectly in case it has multiple tags.

### ISSUE THREAD

**Issue by mmartin** [pazz/alot#1433]
**Describe the bug**
In the thread view, the focused message's summary is rendered incorrectly in case it has multiple tags – only one of the tags has the correct colors, the other ones have their unfocused coloring.

![tags](https://user-images.githubusercontent.com/236237/64474176-e5e8d480-d179-11e9-9de5-776f972b18c2.png)

**Software Versions**
- Python version: 3.6
- Alot version: 0.8.1

**To Reproduce**
Steps to reproduce the behaviour:
1. open a message with multiple tags;
2. see that only one tag has the correct colors.

**Additional notes**
The same problem in the search view is handled by overriding `render` method:
https://github.com/pazz/alot/blob/244180d52f4ace8181bb288e77402c766ad620c1/alot/widgets/search.py#L68-L71

Here is a quick and dirty fix which works for me. I am not familiar enough with Urwid and Alot to fix in properly.
```diff
--- a/alot/widgets/thread.py
+++ b/alot/widgets/thread.py
@@ -53,6 +53,14 @@ class MessageSummaryWidget(urwid.WidgetWrap):
                 cols.append(('fixed', tag_widget.width(), tag_widget))
         line = urwid.AttrMap(urwid.Columns(cols, dividechars=1), attr,
                              focus_att)
+
+        def _render_wrap(size, focus=False):
+            for c in cols:
+                if isinstance(c, tuple):
+                    c[2].set_map('focus' if focus else 'normal')
+            return urwid.AttrMap.render(line, size, focus)
+        line.render = _render_wrap
+
         urwid.WidgetWrap.__init__(self, line)
 
     def __str__(self):
```

**Comment by pazz** [comment]
I cannot reproduce this.
Can you post the relevant part of your theme config?

**Comment by mmartin** [comment]
Default theme has the same problem.

I should have created the screenshot using default theme, sorry about that.

**Comment by mrichar1** [comment]
Can confirm I'm also seeing this bug - independent of the theme used - and the workaround suggested above also works for me (though don't know if that's the 'correct' fix). Also on `0.8.1`

**Comment by pazz** [comment]
Thanks for the bug report and the immediate fix. And apologies for my late reply.
This is really ugly but seems necessary to me: Our widgets should be focussable
but if so, they should flip all contained widgets to their respective "focussed" theming.
urwid does not allow this per se because it assumes that only one of these sub-widgets can be focussed (which is true, we just want to change the visuals).

So, please send this as as PR and I'll merge it. Ideally, you could add a reference to this issue in the code, explaining why this extra bit of code is necessary.
Thanks!
P
