### ISSUE TITLE
Sort threads by subject

### ISSUE THREAD

**Issue by lenormf** [pazz/alot#1510]
Hi,

It'd be nice if users could sort search results by subject. My usecase is grabbing all the notifications that have a "tag" in their subject (e.g. "[foo.com] Title", "[another.io] Notification), and then sorting them.

Thanks!

**Comment by pazz** [comment]
This is not going to happen without a major rewrite of either libnotmuch or the search mode UI.
At the moment, search mode can only list results of a single notmuch query, and those can only be listed by oldest/newest first..

**Comment by lenormf** [comment]
Yea, I noticed NotMuch is quite inflexible on that front, I was hoping that whatever was using the bindings (or the bindings themselves) might be able to work around that…

**Comment by pazz** [comment]
I guess one could hack around with caching the whole result set and then sorting it yourself,
but this may need to introduce some artificial cut-off due to memory constraints..
It could be done, but isn't very natural nor desirable for me personally.
PRs are welcome of course if you want to add that.

I guess the more important upcoming change would be a switch to these new notmuch python bindings.


Quoting Frank LENORMAND (2020-05-15 09:42:23)
