### ISSUE TITLE
configurable "threadline"

### ISSUE THREAD

**Issue by atrent** [pazz/alot#1553]
I would like to /template/ my threadline, e.g. by introducing separators (such as "|" between date and the rest of the line).

I've tried to add a "|" in the theme config file by doing:

`        parts = date,"|",mailcount,tags,authors,subject
`
in the default.theme file, without effect.

Is there a way to customize the line?

**Comment by pazz** [comment]
I don't think this is possible with the current theme configs, no.
I agree that would be nice, so that for instance just like for the statusline one could provide a formated string where placeholders get replaced by date, authors, etc.

The issue is that a threadline is not just a text widget with a single string but instead those are lists of individually themed text widgets displayed next to one another horizontally. This is how you can have different colours for tags for example.

So atm, this is a non-feature but PR's or RFCs would be welcome :)
