### ISSUE TITLE
Add asyncronous 'mark as read' commands

### ISSUE THREAD

**Issue by kazuoteramoto** [pazz/alot#307]
When marking as read (`toggletags unread`) from search buffer (`search tag:unread`) an async tagging cmd can be used to make the interface more responsive, as now the user need to wait to database changes to have the thread removed from the list.

I usually mark as read only by reading the subject, when you have a lot of threads this "waiting for database" can slow you down. I usually change to mutt when doing this because its only update the flags at close and this is not good too, because if something kills mutt I lose all my work in marking as read what I don't really read =].

I propose to have a tagging cmd that postpone the database changes (at least the unread tag), making the UI more responsive.

Another simple solution is to make possible to bind multiples commands, so we can have a

s = 'toggletags unread; move next unread'

(and I think alot don't have a 'move next unread' too)

**Comment by teto** [comment]
Maybe I am doing sthg wrong but the tags displayed along with the title are not refreshed when no-flush is used (e.g, when doing `toggletags --no-flush unread; refresh`, the post is still marked unread).
Also how to call the flush logic ? Is there a way to autoflush on losing focus/exit ?

**Comment by pazz** [comment]
@teto yes, when you don't fush the post *is* still "unread" according to the notmuch database, and only alot adds it to its todo list for later writes. It is arguable if you actually want to change the display in this case but I see that this is confusing.

autoflush on losing focus: that should not be necessary because upon entering focus, the default behaviour is to remove the unread tag *and flush*. Any alternative behaviour would have to be coded either via hooks and keybindings, or justifiable changes to the default codebase, I'm afraid :/

**Comment by teto** [comment]
I meant the window manager focus (i.e., defer the heavyweight operations when the user stops using alot interactively).

> It is arguable if you actually want to change the display in this case but I see that this is confusing.

I agree. At the same time, keeping the UI reactive should be prioritized over the database consistency (I don't care losing a few labelling operations). 

Another approach, I don't mind if the display doesn't reflect my changes immediately  but it is frustating to have the UI block for 1 sec after marking a mail as read. Isn't it possible to run some notmuch request async ? and update the UI once completed. I guess everything is possible, I mean is it a manageable change with alot infrastructure ?
