### ISSUE TITLE
add ability to periodically fire command

### ISSUE THREAD

**Issue by pazz** [pazz/alot#522]

**Comment by lucc** [comment]
I found a way to do this in the hooks file. I just start a new thread which loops and does something every n seconds. On exit the thread gets a signal to terminate. Because I wanted to see the thread working from the main ui I had to start it from some normal hook in order to hand it the main ui instance. (I did not find any way to get the ui in the hooks file. Is there one?)
```python
import threading
import time
exit_event = theading.Event()
def exit():
    exit_event.set()
started = False
def pre_buffer_open(ui, dbm, buf):
    global started
    if not started:
        started = True
        threading.Thread(target=periodical, args=(ui, exit_event)).start()
def periodical(ui, exit_event):
    count = 0
    while not exit_event.is_set():
        time.sleep(5)
        count += 1
        ui.notify('Periodical event fired {} times.'.format(count))
```
