### ISSUE TITLE
Do not quit when there is an active envelope buffer

### ISSUE THREAD

**Issue by tannhuber** [pazz/alot#607]
From time to time it happens that I quit alot by hitting 'q' when it is still sending a mail with a large attachment. The message is then lost without any feedback. Is it possible to deactivate the 'q' key  when an envelope is found? Another possibility would be to send at least a warning. This would be consequential because alot does the same when hitting the 'd' key on an envelope buffer.

**Comment by josch** [comment]
I think this bug is diverging into different problems. What is the actual problem to solve here?

 * a not-yet-sent email is lost because q is accidentally pressed? I solved that problem by putting into my config (I barely ever want to quit a lot and if I really do, I can just close all buffers manually or type the quit command explicitly instead of using the hotkey):

```
[bindings]
    q =
```

 * mail is lost if sending doesn't succeed? I also use msmtp but never experienced that problem. If I loose connection msmtp would return a non-zero exit status and thus the mail would be retained. Maybe this is a bug in msmtp?
 * mail is lost because of power failure. This could be solved by making `$TMP` configurable and by putting something in `editor_cmd` that lets it auto-save every X minutes.

About temporary files vanishing after alot quits, maybe this is because alot does not set `delete=False` when using the tempfile modul and thus the file will be deleted once the file handle is closed which happens when the process quits?

**Comment by lucc** [comment]
This should be fixed in recent master. If I have an envelope buffer open, `:quit` will issue an extra warning prompt (after the potential `bug_on_exit` prompt): `quit without sending message? (y):yes (n):no`. So this can be closed, no?

If you want to change the tempfile handling you should open a new issue/PR.
