### ISSUE TITLE
Thread view should act like a pager

### ISSUE THREAD

**Issue by mturquette** [pazz/alot#820]
alot handles the cursor and reading mail a bit oddly compared to other MUAs.

In particular alot scrolls line by line through the body of an email; this is how a text editor like vim works. Mutt and other MUAs act like a pager; pressing 'j' or 'k' always shifts the whole content of the screen up or down, and never moves the cursor within a given set of displayed text.

Put another way, alot handles text like reading a file in vim. It should support an option to read text like less.

Since alot intermixes the thread with the email body (maybe I should open another issue for that?) we have to be able to scroll text AND collapse/expand, select, {un,re}tag and edit messages within the thread, so some method of selection is still necessary.

**Comment by lucc** [comment]
You can bind different versions of the `move` command to any key you like: look up the [`move` command](
http://alot.readthedocs.org/en/latest/usage/modes/global.html) (especially check the different arguments) and [how to bind it to a key](http://alot.readthedocs.org/en/latest/configuration/key_bindings.html).

**Comment by pazz** [comment]
The thing is that alot itself doesn't manage the scrolling:
it just displays some widgets and then can select which of them is "in focus".
Urwid automagically aligns the widgets on screen so that the focussed on
is visible.

So the choice seems to be to

1) make every line a widget as it is atm or
2) make the whole text "body" of a message one widget.

The problem with the latter is (as far as i remember; there were issues about this)
that sometimes the screen "jumps" from one widget to another in a seemingly
uncontrolled way.

**Comment by mturquette** [comment]
Do you have some code for the “make the whole text body a widget” approach?

**Comment by pazz** [comment]
https://github.com/pazz/alot/pull/645
(let's discuss this in the original issue)
