### ISSUE TITLE
support "to:me" in search

### ISSUE THREAD

**Issue by mturquette** [pazz/alot#822]
In Gmail it's common to use "me" as a special identifier. E.g. a search for "label:unread and to:me".

It would be great to have "to:me" in alot. I'm really not sure if this request should go to alot or to notmuch. Does alot massage the search string at all before passing it to notmuch?

**Comment by pazz** [comment]
Quoting Michael Turquette (2016-01-02 20:24:02)
>    It would be great to have "to:me" in alot. I'm really not sure if this
>    request should go to alot or to notmuch. Does alot massage the search
>    string at all before passing it to notmuch?

It should go to notmuch as alot indeed does not touch the query string at all,
and this is by design for conformity among clients (and also so that i can fwd
requests like this and focus on the interface :)

This might be a good use case for "saved searches", a feature that the emacs
client offers but which unfortunately did not make it into libnotmich afaik,
which is why alot doesnt offer this feature.
