### ISSUE TITLE
To: field with upper case user name causes exception on reply.

### ISSUE THREAD

**Issue by lucc** [pazz/alot#847]
I recieved an email with the user name part of my email address in upper case letters. When I view the email and hit `r` I get this exception:

```
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 633, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/site-packages/alot/commands/globals.py", line 846, in apply
    if self.encrypt or account.encrypt_by_default:
exceptions.AttributeError: 'NoneType' object has no attribute 'encrypt_by_default'
```

If I edit the mail file on disk and change the mail header line from `To: USER@domain.tl` to `To: user@domain.tl` I can use the `reply` command.

In the config file I identify this account with lower case letters: `address = user@domain.tl` and I have set `sign_by_default` and `encrypt_by_default`.

**Comment by genkimarshall** [comment]
Just ran into this myself.

Quick hack fix: right after [this line](https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L805) add `addr = addr.lower()`

Basically the issue is that the next line `account = settings.get_account_by_address(addr)` fails to find the account if you have your email as `User@domain.tl` instead of `user@domain.tl` for example, because the string comparison doesn't work. Email addresses are technically case-sensitive but Postfix seemed to reason that the email was actually for me. Not sure best course of action. Perhaps alot can do the same as Postfix and do case-insensitive. So maybe edit  `settings.get_account_by_address()` as such? Not sure if this is a bad longterm fix though. I would be happy to submit a patch, @pazz do you have any thoughts?

**Comment by lucc** [comment]
Maybe we can add a new option to the account section: `case_sensitive_user_name` which defaults to `True`. And people how use email providers or programs that handle user names case insensitive can set it to `False`.

**Comment by pazz** [comment]
I think whether or not an account can be found due to case sensitive/insensitive matching is a separate issue from fixing this error, which results because no account has been found.
This should not result in a blowup but handled gracefully.

Regarding case (in)sensitivitly, i have no strong feelings either way. Maybe such a setting would be useful for some people..
Forcing case insensitivity would require two things though:
1. as the OP suggests, a `addr.lower()` at the point where we actually look up
2. in the keys constructed in `settings.manager.Manager._account_table` should all be `.lower`ed as well

**Comment by adborden** [comment]
I tried out #863 and although you no longer get the exception, account specific settings wont' get applied which is confusing to the user. Especially confusing are settings like `sent_box`, where the message you just sent doesn't get persisted to the right folder and appears to be missing.

I'd opt for the lowercasing fix.

**Comment by pazz** [comment]
@dcbaker: thoughts on the lower-case hotfix vs. #863 ?
