### ISSUE TITLE
ConfigObj interpolation in config file

### ISSUE THREAD

**Issue by lucc** [pazz/alot#902]
ConfigObj supports interpolation: https://configobj.readthedocs.io/en/latest/configobj.html#string-interpolation

In the theme file this works (see the solarized theme in the example dir) but in the config file it doesn't work for me. I want to use the same realname and send_box etc for different accounts. I have this config file:

```
foo = Lucas Hoffmann
[accounts]
[[one]]
realname = %(foo)s
address = one@example.com
[[two]]
realname = %(foo)s
address = two@example.com
```

alot starts just fine but when i compose a mail the sender is set to `%(foo)s <one@example.com>` instead of `Lucas Hoffmann <one@example.com>`.

I did not find the point in the source where config files and theme files are treated differently. As far as I can see `alot.settings.utils.read_config()` is used for both.

What am I doing wrong/misunderstanding? Can this be fixed?

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2016-10-23 11:16:45)
>    ConfigObj supports interpolation:
>    [1]https://configobj.readthedocs.io/en/latest/configobj.html#string-interpolation
> 
>    In the theme file this works (see the solarized theme in the example dir)
>    but in the config file it doesn't work for me. I want to use the same
>    realname and send_box etc for different accounts. I have this config file:
> 
>  foo = Lucas Hoffmann
>  [accounts]
>  [[one]]
>  realname = %(foo)s
>  address = one@example.com
>  [[two]]
>  realname = %(foo)s
>  address = two@example.com
> 
>    alot starts just fine but when i compose a mail the sender is set to
>    %(foo)s <one@example.com> instead of Lucas Hoffmann <one@example.com>.
> 
>    I did not find the point in the source where config files and theme files
>    are treated differently. As far as I can see
>    alot.settings.utils.read_config() is used for both.


While this is not mentioned in alot's documentation because I really
don't want to debug or provide support for configobj, I agree that this
should work and I'm equally surprized that alot configs and theme files
behave differently.
If you find out why, I welcome a patch, but this is not a priority for
me.

Besides, I am now questioning my initial enthusiasm for configobj
settings as opposed to plain python scripts. Sure, it allows for a
config verification before actually running anything, but the
the code as well as the set up in the SettingsManager etc is not pretty
nor very maintainable..
p

**Comment by pazz** [comment]
just debugging this a bit: in an alot pyshell i did

```
>>> from alot.settings import settings as s
>>> c=s._config
>>> c.interpolation
True
```

So interpolation should work. Indeed it seems to work for global options:

```
foo = FOOO
initial_command = %(foo)s
[accounts]
  [[gmail]]
    realname = %(foo)s
```

.. works as expected. also:

```
>>> c['accounts']['gmail']['realname']
u'FOOO'
```

BUT: If I compose a new mail, the accountprompt lists

```
%(foo)s <patricktotzke@gmail.com>
``` 

So I presume the error is in the ComposeCommand?

**Comment by pazz** [comment]
the issue is here: https://github.com/pazz/alot/blob/master/alot/settings/manager.py#L122
`config['accounts'][acc]` behaves like a dict (it lets you access `c['realname']` with interpolated strings),
but its not a dict, its a ConfigObj. The interpolation takes place in the getter, so if we cast it into a dict then this feature is lost. However, just removing this cast is not the end of the story,
as this is silently done when we use a reference to this object https://github.com/pazz/alot/blob/master/alot/account.py#L52 to be interpreted as keyword parameters.

Bottomline, one needs to read all interesting values from `config['accounts'][acc]` explicitly.

**Comment by pazz** [comment]
I guess this is done now :)
