### ISSUE TITLE
use python code inside alot config file?

### ISSUE THREAD

**Issue by toogley** [pazz/alot#910]
This would helpful, because e.g. python functions can be stored inside a single file (=the alot config) instead of a separate one. That improves maintainability for highly customized configs, IMHO.

* How useful do you consider this feature?
* How difficult is it to implement?

**Comment by pazz** [comment]
I was thinking about this for a while, or rather: If I'd rewrite alot from scratch I'd just use a central
python file for user configs. I'd be happy to have the settings module decluttered. But at this point it might not be so popular as it'd break compatibility..

**Comment by toogley** [comment]
Well my experience is certainly limited, but i think we wouldn't have to rewrite alot: We could implement it like that:

* If there's a `alot/config` file read like before, ignore further steps
* If there's a `alot/pythonconfig` file, read that.

But i'm not sure how difficult this is to maintain.

**Comment by lucc** [comment]
We can argue that we are still in "early" developement as we don't have 1.0 out and hence can also break compatibility and make big changes.

I am not against a python config file. One question to think about is if the file can have a simple enough syntax for new users (non programmers) to be usable. Otherwise we would exclude non programmers from using alot.

I would call the file `~/.config/alot/config.py`.

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2016-12-09 10:52:49)
>    We can argue that we are still in "early" developement as we don't have
>    1.0 out and hence can also break compatibility and make big changes.
> 
>    I am not against a python config file. One question to think about is if
>    the file can have a simple enough syntax for new users (non programmers)
>    to be usable. Otherwise we would exclude non programmers from using alot.
The syntax would be trivial of course:
the file would just define a bunch of constants.

I very much doubt that anyone who isn't able to edit a default config.py
file would be much attracted by alot anyways.
> 
>    I would call the file ~/.config/alot/config.py.

yes: it'd be config.py in $XDG_CONFIG_HOME.

**Comment by toogley** [comment]
> The syntax would be trivial of course: the file would just define a bunch of constants. 

What about defining account specific things? One solution may be to use objects. What are your thoughts about that?

**Comment by pazz** [comment]
Quoting Tobias Angele (2016-12-09 14:22:02)
>    What about defining account specific things? One solution may be to use
>    objects. What are your thoughts about that?

not thought through of course, but I can imagine something like
accounts being a list of dicts, each setting (account)local variables...

**Comment by dcbaker** [comment]
I'm always a bit uncomfortable using executable code for configuration files. Apart from it being a security nightmare, mis-configuration has the potential to cause silent behavioral changes rather than crashing or doing nothing, since it's difficult to tell what is a misconfiguration. Especially in a language like python (especially 2.x) which tries very hard to be liberal with what it accepts. Which brings me to the next problem with using python files for configuration, migrating from python 2.x to 3.x or a hybrid code base. Configurations may only work on one or the other version, or worse it does something different under different versions of python, which would be especially problematic for a hybrid code base. Even people savvy enough to write python may not know about __future__ imports, or compatibility libraries like six.

All of that said, I'm not opposed to changing the config format (I agree that we're pre 1.0 so we could do it), but I would really prefer to keep an declarative syntax for the config files and continue to have a hooks file (or maybe directory?) than move to a python module for configuration.

**Comment by zenhack** [comment]
I share @dcbaker's concerns about using python as a config format.

**Comment by pazz** [comment]
OK, good. Let's stick with configobject for now. We can re-open this issue later if needed.
