### ISSUE TITLE
Mouse scrolling support

### ISSUE THREAD

**Issue by samdmarshall** [pazz/alot#951]
Hi, I was wondering if there is support in `alot` for scrolling up and down using the mouse. I tried binding the urwid scroll event bindings (`mouse press 4`/`mouse press 5`) and those didn't seem to do anything. I saw there were two issues filed about this in the past and from many years ago and unsure of their current status. Is this still on the roadmap, and is there anything that could be done to help move this feature along? Thanks!

**Comment by pazz** [comment]
Hi Sam, welcome to alot. There has no change since #664. I'll close this issue here, we can discuss it there.

It should not be hard to make this work "reasonably well":
Changing the boolean here
https://github.com/pazz/alot/blob/3e8ba6e1380c900945cf2d03694d127021b2c724/alot/ui.py#L99
should allow you to map urwid mouse events, for instance to pageup/down. This would be a welcome patch (with updated default bindings).
HTH,
p

**Comment by samdmarshall** [comment]
Thanks for the quick reply to this, I've put up a new PR to address this.
